- name: Configure eth1/1 as DHCP
  hosts: my-firewall
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'yes'

  - name: set ethernet1/1 as L3
    panos_interface:
      provider: "{{ provider }}"
      if_name: "ethernet1/1"
      mode: "layer3"
      vr_name:
      state: "present"
      commit: "false"

  - name: ethernet1/1.100 as layer3
    panos_l3_subinterface:
      provider: "{{ provider }}"
      name: "ethernet1/1.100"
      tag: 100
      zone_name: "inside"
      vr_name: "vr-1"
      ip: [ "192.168.1.1/24" ]
      state: "present"
